[package]
name = "mnemosyne"
version = "0.1.0"
edition = "2021"

[lib]
name = "mnemosyne"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["std"] }